store: urbansim.h5

build_networks:
  max_distance: 5280 #Distance is feet
  on_ramp_distance: 2640
  parks_distance: 2640
  schools_distance: 5280
  transit_distance: 2640

aggregation_tables:
  - nodes

households_transition:
  add_columns:
    - income_quartile
  total_column: hh #total_number_of_households

jobs_transition:
  add_columns:
    - sector_id
  total_column: number_of_jobs

#DEFAULT LAND COST PER SQ FOOT, Used in the feasibility model
default_land_cost: 12.21

feasibility:
  parcel_filter: newest_building < 2010
  residential_to_yearly: True
  pass_through:
    - oldest_building
    - total_sqft
    - max_far
    - max_dua
    - land_cost
    - residential
    - min_max_fars
    - max_far_from_dua
    - max_height
    - max_far_from_heights
    - building_purchase_price
    - building_purchase_price_sqft
#  msa_id:
#    nonres_price_shifter:
#      0: 0.59
#      1: 0.74
#      2: 1.26
#      3: 1.66
#      4: 1.46
#      5: 1.66
#      6: 1
#    res_price_shifter:
#      0: 0.42
#      1: 0.54
#      2: 1.18
#      3: 1.66
#      4: 1.38
#      5: 1.66
#      6: 1
#  target_luz:
#    0: 69
#    1: 70
#    2: 72
#  luz_shifter:
#    0: 0.78

residential_developer:
  target_vacancy: .08
  min_unit_size: 1000
  bldg_sqft_per_job: 400

non_residential_developer:
  target_vacancy: .49
  bldg_sqft_per_job: 400


# this maps building type ids to general building types
# basically just reduces dimensionality
building_type_map:
  1: Other
  2: Industrial
  3: Industrial
  4: Office
  5: Retail
  6: Other
  7: Other
  8: Other
  9: Other
  10: Other
  11: Other
  12: Other
  13: Other
  14: Other
  15: Other
  16: Other
  17: Other
  18: Other
  19: Residential
  20: Residential
  21: Residential
  22: Other
  23: Other
  24: Other
  25: Other
  26: Other
  27: Other
  28: Other
  29: Other
  30: Other
  31: Other
