store: urbansim.h5

build_networks:
  max_distance: 5280 #Distance is feet
  on_ramp_distance: 2640
  parks_distance: 2640
  schools_distance: 5280
  transit_distance: 2640

aggregation_tables:
  - nodes

households_transition:
  add_columns:
    - income_quartile
  total_column: hh #total_number_of_households